### ISSUE TITLE
first 

### ISSUE THREAD

**Issue by sec13b** [RiritoNinigaya/DisableUAC_CppEdition#5]
first prob i get missing MSVCP140D.dll

**Comment by RiritoNinigaya** [comment]
Try Switch to Release Version!!!

**Comment by RiritoNinigaya** [comment]
or Install C++ Runtime 2005-2023

**Comment by sec13b** [comment]
if you use it in your pentesting  internal , more servers dont have C++ RUNTIME.

**Comment by sec13b** [comment]
![image](https://github.com/RiritoFrancois/DisableUAC_CppEdition/assets/123419537/27d92a0d-b23d-4c07-92cd-0dcf3f8ccaf6)

![image](https://github.com/RiritoFrancois/DisableUAC_CppEdition/assets/123419537/c3239ab2-b3fc-4159-8425-2ac250f501a3)

**Comment by RiritoNinigaya** [comment]
> if you use it in your pentesting internal , more servers dont have C++ RUNTIME.

i know

**Comment by RiritoNinigaya** [comment]
> ![image](https://private-user-images.githubusercontent.com/123419537/296605143-27d92a0d-b23d-4c07-92cd-0dcf3f8ccaf6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjk1NDEsIm5iZiI6MTcwNTMyOTI0MSwicGF0aCI6Ii8xMjM0MTk1MzcvMjk2NjA1MTQzLTI3ZDkyYTBkLWIyM2QtNGMwNy05MmNkLTBkY2YzZjhjY2FmNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxNDM0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOTg4MmFkNTI2ZDJiZmZmZjFjMThmMGZmODZiZTljMGYzYjcxMjRiYTYzOTc0OWNiNjM3NDU2ZWZlMzQxMDE1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.OLDPLXW3IOf55dSN6vmTz1gAJ_PKR8mAV0QtuSC3QA8)
> 
> ![image](https://private-user-images.githubusercontent.com/123419537/296605105-c3239ab2-b3fc-4159-8425-2ac250f501a3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUzMjk1NDEsIm5iZiI6MTcwNTMyOTI0MSwicGF0aCI6Ii8xMjM0MTk1MzcvMjk2NjA1MTA1LWMzMjM5YWIyLWIzZmMtNDE1OS04NDI1LTJhYzI1MGY1MDFhMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNVQxNDM0MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzA4MjEzYjZkOTcyMjZjZmZmNTdiZDk2NWRjNTBhYWJlNGFkNTU4ZDBmNjA1YWRjYzRjNzUxYzdlOGVjYTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.H-b85jy1xQqEjgUin9sms8TQGR7-hNpXi7YV-7Ec4Ds)

You have Windows 8 or Windows 10?

**Comment by sec13b** [comment]
windows server 2012

**Comment by RiritoNinigaya** [comment]
> windows server 2012

works only on windows 8, windows 8.1, windows 10 and windows 11

**Comment by sec13b** [comment]
OK. I hope test soon.
Thank you
